pc<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
pc$Date<-as.Date(pc$Date,"%d/%m/%Y")
pc1<-subset(pc,Date>=as.Date('2007-02-1') & Date<=as.Date('2007-02-02'))
pc1$Global_active_power<-as.numeric(as.character(pc1$Global_active_power))
pc1$Time<-paste(pc1$Date,pc1$Time,sep=" ")
pc1$Time<-strptime(pc1$Time, "%Y-%m-%d %H:%M:%S")
png("plot2.png",width=480,height=480,units="px")
plot(pc1$Time,pc1$Global_active_power,xlab="", ylab="Global Active Power (killowatts)", type="n")
lines(pc1$Time,pc1$Global_active_power,type="l")
dev.off()
