pc<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
pc$Date<-as.Date(pc$Date,"%d/%m/%Y")
pc1<-subset(pc,Date>=as.Date('2007-02-1') & Date<=as.Date('2007-02-02'))
pc1$Global_active_power<-as.numeric(as.character(pc1$Global_active_power))
pc1$Global_reactive_power<-as.numeric(as.character(pc1$Global_reactive_power))
pc1$Voltage<-as.numeric(as.character(pc1$Voltage))
pc1$Time<-paste(pc1$Date,pc1$Time,sep=" ")
pc1$Time<-strptime(pc1$Time, "%Y-%m-%d %H:%M:%S")
png("plot4.png",width=480,height=480,units="px")
par(mfrow=c(2,2))
plot(pc1$Time,pc1$Global_active_power,xlab="", ylab="Global Active Power (killowatts)", type="n")
lines(pc1$Time,pc1$Global_active_power,type="l")
plot(pc1$Time,pc1$Voltage,xlab="datetime", ylab="Voltage", type="n")
lines(pc1$Time,pc1$Voltage,type="l")
plot(pc1$Time,pc1$Sub_metering_1,xlab="", ylab="Energy sub metering", type="n")
lines(pc1$Time,pc1$Sub_metering_1,type="l")
lines(pc1$Time,pc1$Sub_metering_2,type="l",col="red")
lines(pc1$Time,pc1$Sub_metering_3,type="l",col="blue")
legend(x="topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1, col=c("black","red","blue"))
plot(pc1$Time,pc1$Global_reactive_power,xlab="datetime", ylab="Global_reactive_power", type="n")
lines(pc1$Time,pc1$Global_reactive_power,type="l")
dev.off()